# Generated by Django 3.2.15 on 2022-08-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meetuo',
            new_name='Meetup',
        ),
    ]
