# Generated by Django 3.2.15 on 2022-08-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_rename_meetuo_meetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(default='defult_image', upload_to='images'),
            preserve_default=False,
        ),
    ]
